# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  init:
    cmds:
      - uv venv --clear
      - uv pip install -r fetcher/requirements.txt
  build:
    dir: fetcher
    cmds:
      - docker build -t fetcher .
  run:
    cmds:
      - docker run --rm -i -t --env GITHUB_TOKEN -v ${PWD}:/app fetcher -a -vv
  debug:
    cmds:
      - docker run --rm -i -t --env GITHUB_TOKEN -v ${PWD}:/app --entrypoint /bin/sh fetcher