gh_repo = "astral-sh/uv"
name="uv"
license="MIT"
arch="x86_64"
url="https://docs.astral.sh/uv/"
description = "An extremely fast Python package and project manager, written in Rust."
maintainer = "The Astral Contributors"
binaries = ["uv", "uvx"]
bindir = "/usr/local/bin"
gh_asset_regex = "^uv-x86_64-unknown-linux-musl.tar.gz$"
strip_components = 1
pkgtypes = "apk"
depends = "musl"